[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
dao_voting = "dAo8nCHebC5n737hY7iKvYbqnJZK9BDQURsddiT2Q7Q"

[programs.localnet]
dao_voting = "dAo8nCHebC5n737hY7iKvYbqnJZK9BDQURsddiT2Q7Q"

[programs.mainnet]
dao_voting = "dAo8nCHebC5n737hY7iKvYbqnJZK9BDQURsddiT2Q7Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/xpsolitesol/PsoToaHqn3GsmCgbSfb9DSXtgJoXsjZv7xWQ3c4zz4o.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
